org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.21.1
neo_version=21.1.77
mod_id=copycatplusadditions
mod_name=Copycats+ Additions
mod_version=1.0.0
mod_group_id=com.agent772
mod_authors=Agent772

# Find latest at: https://modrinth.com/mod/copycats-plus/versions?g=1.21.1&l=neoforge
copycats_version=2.2.1+mc1.21.1-neoforge
