modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "copycatplusadditions"
version = "${file.jarVersion}"
displayName = "Copycats+ Additions"
description = '''
Adds extra block variants to Copycats+, including vertical slope layers and more to come.
'''
authors = "Agent772"

[[dependencies.copycatplusadditions]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.copycatplusadditions]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.22)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.copycatplusadditions]]
    modId = "copycatsplus"
    type = "required"
    versionRange = "[2,)"
    ordering = "AFTER"
    side = "BOTH"
